variables: 
  WORKDIR: /var/deploy/${CI_COMMIT_BRANCH}/${CI_COMMIT_SHORT_SHA}
stages:
  - main
  - staging
  - test

build-main:
    stage: main
    tags:
        - rent
    script:
        - rsync -tar --exclude='.git*' --exclude='readme.md'  --stats --no-perms . ${WORKDIR}
        - echo ${ENV} ${WORKDIR}/src/env.js
        - echo ${ECOSYSTEM} ${WORKDIR}/ecosystem.config.js
        - cd ${WORKDIR} && yarn
        - cd ${WORKDIR} && yarn build
        - ln -sfT ${WORKDIR} /var/www/new.rent.myauto.ge


