pipelines:
  branches:
    test:
      - step:
          runs-on:
            - self.hosted
            - linux.shell
          script:
            - WORKDIR="/var/deploy"
            - mkdir -p $WORKDIR/$BITBUCKET_BRANCH/$BITBUCKET_COMMIT
            - cp -r $PWD $WORKDIR/$BITBUCKET_BRANCH/$BITBUCKET_COMMIT/
            - ADIR="$WORKDIR/$BITBUCKET_BRANCH/$BITBUCKET_COMMIT/build"
            - cd $WORKDIR && cp env.example $ADIR/src/env.js
            - cd $WORKDIR && cp ecosystem.config.js $ADIR/
            - cd $ADIR && yarn
            - cd $ADIR && yarn build
            - ln -sfT $ADIR /var/www/new.rent.myauto.ge
            - cd /var/www/new.rent.myauto.ge && (pm2 reload ecosystem.config.js || pm2 start ecosystem.config.js)
            - cd $WORKDIR/$BITBUCKET_BRANCH && ls -t | tail -n +3 | sudo xargs -I {} rm -r {}